### ISSUE TITLE
Simplify toolchain selection for lints

### ISSUE THREAD

**Issue by z8674558** [internet2-org/rust-aluvm#38]
e.g. `fmt` check uses `nightly` while `clippy` is on `stable`. Since `fmt`and `clippy` yells at different points on `stable` and `nightly`, we would need to switch the compiler frequently on the local machine

**Comment by dr-orlovsky** [comment]
the original plan was to use stable everywhere. But it become apparent that many important `fmt` features require nightly, so I switched on it. I am bit afraid of nightly `clippy` since it unstable: what was passing it yesterday may not pass it tomorrow and we may have constant CI breaks randomly appearing.

But I am not satisfied with this situation and would like to see better solution. Do you have anything to suggest which may help avoiding this issues?

**Comment by z8674558** [comment]
maybe we can use [cargo-make](https://github.com/sagiegurari/cargo-make) and run a "wrapped" fmt with `cargo make fmt`, with the task definition like below:

```
[tasks.fmt]
description = "cargo fmt with nightly toolchain"
workspace = false
command = "cargo"
args = ["+nightly", "fmt"]
```

**Comment by dr-orlovsky** [comment]
I like the idea!
