### ISSUE TITLE
`CoreRegs::default()` causes stack overflow

### ISSUE THREAD

**Issue by z8674558** [internet2-org/rust-aluvm#40]
## Current Behavior
```rust
#[test]
fn my_test() { let _register = CoreRegs::default(); }
```

fails with

```
thread 'isa::exec::tests::my_test' has overflowed its stack
fatal runtime error: stack overflow
```

## Cause
https://github.com/internet2-org/rust-aluvm/blob/a7e64abd4a7058bf9f06886452147810b4a5cf6d/src/reg/core_regs.rs#L99
With `Box<[LibSite; CALL_STACK_SIZE]>`, the value would be allocated to stack first, but `CALL_STACK_SIZE = 1 << 16` is too big, resuting in overflow.

## Possible Solutions
Use `Vec<LibSite>` instead.

## Related Issues
https://github.com/rust-lang/rust/issues/53827

**Comment by z8674558** [comment]
It is a bit weird that
https://github.com/internet2-org/rust-aluvm/blob/a7e64abd4a7058bf9f06886452147810b4a5cf6d/src/isa/asm.rs#L39 do not fail, but when I modified `CALL_STACK_SIZE` to `1 << 18`, this also overflowed. So most likely `1 << 16` is near the boundary

**Comment by dr-orlovsky** [comment]
This is bad - and caused by rust compiler bug. It may be changed with stabilizing alternative `box` syntax, but nobody knows when (and would) it happen.

The worst is that this limits for the size are platform-dependent and will overflow on different platforms at different boundaries...

Vec seems to be the only solution here, you are right.
